### ISSUE TITLE
Build an adaptive app with adaptive layout: Android Basics with Compose

### ISSUE THREAD

**Issue by tugceaktepe** [google-developer-training/basic-android-kotlin-compose-training-reply-app#14]
[In step 5 - Add automated test for adaptive apps ](https://developer.android.com/codelabs/basic-android-kotlin-compose-adaptive-content-for-large-screens?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-4-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-adaptive-content-for-large-screens#4)

Hi there,
I want to run all tests in solution branch(main) but test named "expandedDevice_selectedEmailEmailRetained_afterConfigChange" gives error below. 
Is there anyone run this test successfully ? 

```
java.lang.AssertionError: Failed to perform isDisplayed check.
Reason: Expected exactly '1' node but could not find any node that satisfies: (Text + EditableText contains 'We’re having the best time on the coast! We just witnessed such an amazing sunset and sunrise on the beach. We’re going to be here for another week. Come join us!

Cheers,
Stef and Michael' (ignoreCase: false))


at androidx.compose.ui.test.SemanticsNodeInteraction.fetchOneOrDie(SemanticsNodeInteraction.kt:145)
at androidx.compose.ui.test.SemanticsNodeInteraction.fetchSemanticsNode(SemanticsNodeInteraction.kt:79)
at androidx.compose.ui.test.AndroidAssertions_androidKt.checkIsDisplayed(AndroidAssertions.android.kt:29)
at androidx.compose.ui.test.AssertionsKt.assertIsDisplayed(Assertions.kt:33)
at com.example.reply.test.ReplyAppStateRestorationTest.expandedDevice_selectedEmailEmailRetained_afterConfigChange(ReplyAppStateRestorationTest.kt:69)
 
```

**Comment by sathisse** [comment]
See issue #16 for a fix.
